#ifndef PE_MUTATOR_H
#define PE_MUTATOR_H

#pragma once

/* Generated with cbindgen:0.29.2 */

/* Auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

#define PE_MUTATE_CATEGORY_NONE 0

#define PE_MUTATE_CATEGORY_ARCHITECTURE 1

#define PE_MUTATE_CATEGORY_HEADERS (1 << 1)

#define PE_MUTATE_CATEGORY_SECTIONS (1 << 2)

#define PE_MUTATE_CATEGORY_ASSEMBLY (1 << 3)

#define PE_MUTATE_CATEGORY_DATA_DIRECTORIES (1 << 4)

#define PE_MUTATE_CATEGORY_OVERLAY (1 << 5)

#define PE_MUTATE_CATEGORY_ALL 63

#define PE_MUTATE_MUTATION_NONE 0

#define PE_MUTATE_MUTATION_ARCHITECTURE 1

#define PE_MUTATE_MUTATION_SECTION_COUNT (1 << 1)

#define PE_MUTATE_MUTATION_SECTION_HEADER (1 << 2)

#define PE_MUTATE_MUTATION_SECTION_BODY (1 << 3)

#define PE_MUTATE_MUTATION_ENTRY_POINT (1 << 4)

#define PE_MUTATE_MUTATION_EXECUTABLE_CHUNK_ASSEMBLY (1 << 5)

#define PE_MUTATE_MUTATION_OVERLAY (1 << 6)

#define PE_MUTATE_MUTATION_DATA_DIRECTORY_ENTRY (1 << 7)

#define PE_MUTATE_MUTATION_EXPORT_DIRECTORY (1 << 8)

#define PE_MUTATE_MUTATION_RESOURCE_DIRECTORY (1 << 9)

#define PE_MUTATE_MUTATION_ALL 1023

enum PeMutateStatus
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  Ok = 0,
  NullPointer = 1,
  ParseError = 2,
  BufferTooSmall = 3,
  InternalError = 4,
};
#ifndef __cplusplus
typedef uint32_t PeMutateStatus;
#endif // __cplusplus

typedef struct PeMutateCfg {
  uint64_t seed;
  size_t min_stack_depth;
  size_t max_stack_depth;
  size_t overlay_max_len;
  uint64_t enabled_categories;
  uint64_t enabled_mutations;
} PeMutateCfg;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

PeMutateStatus pe_mutate_bytes(const uint8_t *in_buf,
                               size_t in_len,
                               uint8_t *out_buf,
                               size_t out_cap,
                               size_t *out_len,
                               const struct PeMutateCfg *cfg);

PeMutateStatus pe_last_error_message(char *out_buf, size_t out_cap, size_t *out_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PE_MUTATOR_H */
